services:
  - type: web
    name: blogsite
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate && gunicorn blog_main.wsgi:application
