# Generated by Django 5.1.7 on 2025-03-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auhor',
            new_name='author',
        ),
    ]
