# Generated by Django 5.1.7 on 2025-09-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_comment_is_spam_comment_reason_comment_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/%Y/%m/%d'),
        ),
    ]
